/**
 * This file was generated by @pikku/cli@0.12.15
 */
/**
 * This provides the structure needed for TypeScript to be aware of channels
 */




export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentResumeCallerInput = { agentName: string; runId: string; toolCallId: string; approved: boolean; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type HttpOptionsRpcRpcNameInput = { rpcName: string; }
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type ProcessReminderInput = {
    todoId: string;
    userId: string;
}
export type ProcessReminderOutput = {
    processed: boolean;
    message: string;
}
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }

interface ChannelHandler<I, O> {
    input: I;
    output: O;
}

export type ChannelsMap = {
};

export type ChannelDefaultHandlerOf<Channel extends keyof ChannelsMap> =
    ChannelsMap[Channel]['defaultMessage'] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;

export type ChannelWiringHandlerOf<
    Channel extends keyof ChannelsMap, 
    Route extends keyof ChannelsMap[Channel]['routes'], 
    Method extends keyof ChannelsMap[Channel]['routes'][Route],
> =
    ChannelsMap[Channel]['routes'][Route][Method] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;
