/**
 * This file was generated by @pikku/cli@0.12.0
 */
import type { SingletonServices } from '../types/application-types.d.js'
import type { Services } from '../types/application-types.d.js'

// Singleton services map: true if required, false if available but unused
export const requiredSingletonServices = {
  'aiAgentRunner': false,
  'aiRunState': false,
  'aiStorage': false,
  'config': true,
  'deploymentService': false,
  'eventHub': false,
  'jwt': false,
  'logger': true,
  'queueService': false,
  'schedulerService': false,
  'schema': true,
  'secrets': true,
  'todoStore': true,
  'variables': true,
  'workflowService': false,
} as const

// Wire services map: true if required, false if available but unused
export const requiredWireServices = {
} as const

// Type exports
export type RequiredSingletonServices = Pick<SingletonServices, 'config' | 'logger' | 'schema' | 'secrets' | 'todoStore' | 'variables'> & Partial<Omit<SingletonServices, 'config' | 'logger' | 'schema' | 'secrets' | 'todoStore' | 'variables'>>

export type RequiredWireServices = Partial<Services>
