/**
 * This file was generated by @pikku/cli@0.12.0
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */





export type ProcessReminderInput = {
    todoId: string;
    userId: string;
}
export type ProcessReminderOutput = {
    processed: boolean;
    message: string;
}
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type HttpOptionsRpcAgentAgentNameInput = { agentName: string; }
export type HttpOptionsRpcAgentAgentNameStreamInput = { agentName: string; }
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type HttpOptionsRpcRpcNameInput = { rpcName: string; }

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type HttpOptionsRpcAgentAgentNameInputParams = Pick<HttpOptionsRpcAgentAgentNameInput, 'agentName'> & {}
export type HttpOptionsRpcAgentAgentNameInputBody = Omit<HttpOptionsRpcAgentAgentNameInput, 'agentName'> & {}
export type AgentCallerInputParams = Pick<AgentCallerInput, 'agentName'> & {}
export type AgentCallerInputBody = Omit<AgentCallerInput, 'agentName'> & {}
export type HttpOptionsRpcAgentAgentNameStreamInputParams = Pick<HttpOptionsRpcAgentAgentNameStreamInput, 'agentName'> & {}
export type HttpOptionsRpcAgentAgentNameStreamInputBody = Omit<HttpOptionsRpcAgentAgentNameStreamInput, 'agentName'> & {}
export type AgentStreamCallerInputParams = Pick<AgentStreamCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputBody = Omit<AgentStreamCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputParams = Pick<AgentApproveCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputBody = Omit<AgentApproveCallerInput, 'agentName'> & {}
export type HttpOptionsRpcRpcNameInputParams = Pick<HttpOptionsRpcRpcNameInput, 'rpcName'> & {}
export type HttpOptionsRpcRpcNameInputBody = Omit<HttpOptionsRpcRpcNameInput, 'rpcName'> & {}
export type RpcCallerInputParams = Pick<RpcCallerInput, 'rpcName'> & {}
export type RpcCallerInputBody = Omit<RpcCallerInput, 'rpcName'> & {}

interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
  readonly '/rpc/agent/:agentName/stream': {
    readonly GET: HTTPWiringHandler<AgentStreamCallerInput, null>,
    readonly OPTIONS: HTTPWiringHandler<HttpOptionsRpcAgentAgentNameStreamInput, unknown>,
  },
  readonly '/rpc/agent/:agentName': {
    readonly POST: HTTPWiringHandler<AgentCallerInput, null>,
    readonly OPTIONS: HTTPWiringHandler<HttpOptionsRpcAgentAgentNameInput, unknown>,
  },
  readonly '/rpc/agent/:agentName/approve': {
    readonly POST: HTTPWiringHandler<AgentApproveCallerInput, null>,
  },
  readonly '/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>,
    readonly OPTIONS: HTTPWiringHandler<HttpOptionsRpcRpcNameInput, unknown>,
  },
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  