/**
 * This file was generated by @pikku/cli@0.12.0
 */
/**
 * This provides the structure needed for typescript to be aware of Queue workers and their input/output types
 */




export type ProcessReminderInput = {
    todoId: string;
    userId: string;
}
export type ProcessReminderOutput = {
    processed: boolean;
    message: string;
}
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type HttpOptionsRpcAgentAgentNameInput = { agentName: string; }
export type HttpOptionsRpcAgentAgentNameStreamInput = { agentName: string; }
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type HttpOptionsRpcRpcNameInput = { rpcName: string; }

import type { QueueJob } from '@pikku/core/queue'

interface QueueHandler<I, O> {
    input: I;
    output: O;
}

export type QueueMap = {
  readonly 'todo-reminders': QueueHandler<ProcessReminderInput, ProcessReminderOutput>,
};


type QueueAdd = <Name extends keyof QueueMap>(
  name: Name,
  data: QueueMap[Name]['input'],
  options?: {
    priority?: number
    delay?: number
    attempts?: number
    removeOnComplete?: number
    removeOnFail?: number
    jobId?: string
  }
) => Promise<string>

type QueueGetJob = <Name extends keyof QueueMap>(
  name: Name,
  jobId: string
) => Promise<QueueJob<QueueMap[Name]['input'], QueueMap[Name]['output']> | null>

export type TypedPikkuQueue = {
  add: QueueAdd;
  getJob: QueueGetJob;
}
  