/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * This provides the structure needed for typescript to be aware of Queue workers and their input/output types
 */



export type ProcessReminderInput = unknown
export type ProcessReminderOutput = unknown
export type GreetInput = { name: string; greeting?: string; }
export type GreetOutput = { message: string; timestamp: number; serverPort: number; }
export type RemoteGreetInput = { name: string; greeting?: string; }
export type RemoteGreetOutput = { message: string; timestamp: number; serverPort: number; }
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type OnTestEventInput = unknown
export type OnTestEventOutput = unknown
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type PikkuFn_src_wirings_rpc_wiring_ts_L31C9Input = { rpcName: string; }

import type { QueueJob } from '@pikku/core/queue'

interface QueueHandler<I, O> {
    input: I;
    output: O;
}

export type QueueMap = {
};


type QueueAdd = <Name extends keyof QueueMap>(
  name: Name,
  data: QueueMap[Name]['input'],
  options?: {
    priority?: number
    delay?: number
    attempts?: number
    removeOnComplete?: number
    removeOnFail?: number
    jobId?: string
  }
) => Promise<string>

type QueueGetJob = <Name extends keyof QueueMap>(
  name: Name,
  jobId: string
) => Promise<QueueJob<QueueMap[Name]['input'], QueueMap[Name]['output']> | null>

export type TypedPikkuQueue = {
  add: QueueAdd;
  getJob: QueueGetJob;
}
  