/**
 * This file was generated by @pikku/cli@0.12.0
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core'
import { onTestEvent } from '../../src/functions/trigger.functions.js'

addFunction('onTestEvent', onTestEvent)