/**
 * This file was generated by @pikku/cli@0.12.0
 */
import { addSchema } from '@pikku/core/schema'

import * as ProcessReminderInput from './schemas/ProcessReminderInput.schema.json' with { type: 'json' }
addSchema('ProcessReminderInput', ProcessReminderInput)


import * as ProcessReminderOutput from './schemas/ProcessReminderOutput.schema.json' with { type: 'json' }
addSchema('ProcessReminderOutput', ProcessReminderOutput)


import * as TestEventTriggerInput from './schemas/TestEventTriggerInput.schema.json' with { type: 'json' }
addSchema('TestEventTriggerInput', TestEventTriggerInput)


import * as TestEventTriggerOutput from './schemas/TestEventTriggerOutput.schema.json' with { type: 'json' }
addSchema('TestEventTriggerOutput', TestEventTriggerOutput)


import * as OnTestEventInput from './schemas/OnTestEventInput.schema.json' with { type: 'json' }
addSchema('OnTestEventInput', OnTestEventInput)


import * as OnTestEventOutput from './schemas/OnTestEventOutput.schema.json' with { type: 'json' }
addSchema('OnTestEventOutput', OnTestEventOutput)


import * as AgentCallerInput from './schemas/AgentCallerInput.schema.json' with { type: 'json' }
addSchema('AgentCallerInput', AgentCallerInput)


import * as AgentStreamCallerInput from './schemas/AgentStreamCallerInput.schema.json' with { type: 'json' }
addSchema('AgentStreamCallerInput', AgentStreamCallerInput)


import * as AgentApproveCallerInput from './schemas/AgentApproveCallerInput.schema.json' with { type: 'json' }
addSchema('AgentApproveCallerInput', AgentApproveCallerInput)


import * as HttpOptionsRpcAgentAgentNameInput from './schemas/HttpOptionsRpcAgentAgentNameInput.schema.json' with { type: 'json' }
addSchema('HttpOptionsRpcAgentAgentNameInput', HttpOptionsRpcAgentAgentNameInput)


import * as HttpOptionsRpcAgentAgentNameStreamInput from './schemas/HttpOptionsRpcAgentAgentNameStreamInput.schema.json' with { type: 'json' }
addSchema('HttpOptionsRpcAgentAgentNameStreamInput', HttpOptionsRpcAgentAgentNameStreamInput)


import * as RpcCallerInput from './schemas/RpcCallerInput.schema.json' with { type: 'json' }
addSchema('RpcCallerInput', RpcCallerInput)


import * as HttpOptionsRpcRpcNameInput from './schemas/HttpOptionsRpcRpcNameInput.schema.json' with { type: 'json' }
addSchema('HttpOptionsRpcRpcNameInput', HttpOptionsRpcRpcNameInput)
